# define our source to loook for gems
source 'http://rubygems.org/'

gem 'sinatra'
gem 'omniauth-google-oauth2'
#gem 'mongoid',  '4.0.2'
gem 'mongoid'
gem 'json','1.8.6'
gem 'colorize'
gem 'bson'
gem 'feedjira'
gem 'feedbag'
gem 'sinatra-flash'
gem 'fastercsv'
gem 'sanitize'
#gem 'mongoid-compatibility', '0.4.1'
#gem 'mongoid_fulltext'
gem 'i18n','0.8.0'
gem 'activesupport','4.2.7.1'
gem 'nokogiri','1.10.4'
#gem 'mustermann','0.4.0'
gem "chartkick"
# gem 'timber', '~> 2.1'
gem 'puma'
gem 'mongoid_search'
gem 'http'